FoodAppMiniProject/Controllers/DishController.cs
using FoodAppMiniProject.Helpers;
using FoodAppMiniProject.Models;
using FoodAppMiniProject.Services;
using Microsoft.AspNetCore.Mvc;

namespace FoodAppMiniProject.Controllers
{
    public class DishController : Controller
    {
        private readonly IDishService _dishService;
        private readonly IFileUploadService _ImageUploadService;

        public DishController(IDishService dishService, IFileUploadService ImageUploadService)
        {
            _dishService = dishService;
            _ImageUploadService = ImageUploadService;
        }

        [HttpGet]
        public IActionResult ViewDishes()
        {
            var admin = SessionHelper.GetObjectFromJson<Admin>(HttpContext.Session, "admin");
            if (admin != null)
            {
                ViewBag.Admin = admin.Name;
            }
            else
            {
                return RedirectToRoute(new { controller = "Admin", action = "AdminLogin" });
            }
            return View(_dishService.GetAllDishes());
        }

        [HttpGet]
        public IActionResult AddDish()
        {
            var user = SessionHelper.GetObjectFromJson<User>(HttpContext.Session, "admin");
            if (user != null)
            {
                ViewBag.Admin = user.Name;
            }
            else
            {
                return RedirectToRoute(new { controller = "Admin", action = "AdminLogin" });
            }
            return View();
        }

        [HttpPost]
        public IActionResult AddDish(IFormFile file,AddDishViewModel viewModel)
        {
            string Filepath = "";
            if (file != null)
            {
                Filepath = _ImageUploadService.UploadImage(file);
            }
            var admin = SessionHelper.GetObjectFromJson<Admin>(HttpContext.Session, "admin");

            Dish dish = new Dish() { DishName = viewModel.DishName, About = viewModel.About, Price = viewModel.Price };
            dish.AddedBy= admin.Id;
            dish.Img = Filepath;
            _dishService.CreateNewDish(dish);
            TempData["type"] = "success";
            TempData["msg"] = "Dish Added Successfully";
            return RedirectToAction("AddDish");
        }


        [HttpGet]
        public IActionResult DeleteDish(int id)
        {
            _dishService.DeleteDish(id);
            return RedirectToAction("ViewDishes");
        }

        [HttpGet]
        public IActionResult UpdateDish(int id)
        {
            var user = SessionHelper.GetObjectFromJson<User>(HttpContext.Session, "admin");
            if (user != null)
            {
                ViewBag.Admin = user.Name;
            }
            else
            {
                return RedirectToRoute(new { controller = "Admin", action = "AdminLogin" });
            }
            var dishes = _dishService.GetAllDishes().ToList();
            Dish dish = dishes.Where(item=>item.Id == id).FirstOrDefault();
            return View(dish);
        }

        [HttpPost]
        public IActionResult UpdateDish(IFormFile file, Dish viewModel)
        {
            string Filepath = "";
            if (file != null)
            {
                Filepath = _ImageUploadService.UploadImage(file);
            }
            var admin = SessionHelper.GetObjectFromJson<Admin>(HttpContext.Session, "admin");

            List<Dish> dishes = _dishService.GetAllDishes();
            Dish dish = dishes.Where(item => item.Id == viewModel.Id).FirstOrDefault();
            dish.DishName = viewModel.DishName;
            dish.About = viewModel.About;
            dish.Price = viewModel.Price;
            if (file!=null)
            {
                dish.Img = Filepath;
            }
            _dishService.UpdateDish(dish);
            TempData["type"] = "success";
            TempData["msg"] = "Dish Updated Successfully";
            return RedirectToAction("ViewDishes");
        }

        public IActionResult Details(int id)
        {
            var admin = SessionHelper.GetObjectFromJson<Admin>(HttpContext.Session, "admin");
            if (admin != null)
            {
                ViewBag.Admin = admin.Name;
            }
            else
            {
                return RedirectToRoute(new { controller = "Admin", action = "AdminLogin" });
            }

            Dish dish = _dishService.GetAllDishes().Where(i => i.Id == id).FirstOrDefault();
            return View(dish);
        }
    }
}

FoodAppMiniProject/Controllers/OrderController.cs
using FoodAppMiniProject.Helpers;
using FoodAppMiniProject.Models;
using FoodAppMiniProject.Services;
using Microsoft.AspNetCore.Mvc;

namespace FoodAppMiniProject.Controllers
{
    public class OrderController : Controller
    {
        IOrderService _orderService;
        ICartService _cartService;

        public OrderController(IOrderService userService,ICartService cartservice)
        {
            _orderService = userService;
            _cartService = cartservice;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            var user = SessionHelper.GetObjectFromJson<User>(HttpContext.Session, "user");
            List<Cart> items = _cartService.GetAllCartItems(user.Id);
            string invoiceNo = Guid.NewGuid().ToString();
            List<Order> orders = new List<Order>();
            items.ForEach(item =>
            {
                orders.Add(new Order()
                {
                    DishId = item.DishId,
                    Invoice = invoiceNo,
                    Qantity = item.Quantity,
                    UserId = user.Id,
                    Price = item.Dish.Price * item.Quantity,
                    Status = "Ordered"
                });
            });
            bool res = _orderService.AddOrderBulk(orders);
            if(res == true)
            {
                _cartService.DeleteFromCartBulk(items);
            }

            if(res == true)
            {
                TempData["type"] = "success";
                TempData["msg"] = "Order Placed Successfully";
            }
            return RedirectToRoute(new { controller = "Home", action = "Index" });
        }

        [HttpGet]
        public IActionResult ViewOrder()
        {
            var user = SessionHelper.GetObjectFromJson<User>(HttpContext.Session, "user");
            if (user != null)
            {
                ViewBag.User = user.Name;
            }
            else
            {
                return RedirectToRoute(new { controller = "User", action = "UserLogin" });
            }
            var olist = _orderService.GetAllOrders(user.Id).DistinctBy(item=>item.Invoice);
            return View(olist);
        }

        [HttpGet]
        public IActionResult ViewOrderDetails(string id)
        {
            Console.WriteLine("INVOICE : ##### ",id);
            var user = SessionHelper.GetObjectFromJson<User>(HttpContext.Session, "user");
            if (user != null)
            {
                ViewBag.User = user.Name;
            }
            else
            {
                return RedirectToRoute(new { controller = "User", action = "UserLogin" });
            }
            var olist = _orderService.GetAllOrders(user.Id).Where(item => item.Invoice == id).ToList();
            User u = olist.First().User;
            ViewBag.Address = u.Address;
            ViewBag.Invoice = id;
            double orderTotal = 0;
            olist.ForEach(o =>
            {
                orderTotal += o.Qantity * o.Dish.Price;
            });
            ViewBag.OrderTotal = orderTotal;
            return View(olist);
        }



        [HttpGet]
        public IActionResult ViewOrderAdmin()
        {
            var user = SessionHelper.GetObjectFromJson<User>(HttpContext.Session, "admin");
            if (user!= null)
            {
                ViewBag.Admin = user.Name;
            }
            else
            {
                return RedirectToRoute(new { controller = "Admin", action = "AdminLogin" });
            }
            var olist = _orderService.GetAllOrders();
            return View(olist);
        }


        [HttpGet]
        public IActionResult AdminOrderDetails(Order o)
        {
            var order = _orderService.GetAllOrders().ToList();
            return View(order.Where(item => item.Id == o.Id).FirstOrDefault());
        }

        [HttpGet]
        public IActionResult ProcessOrder(Order o)
        {
            //ProcessOrderViewModel orderModel = new ProcessOrderViewModel();
            //orderModel.Id = o.Id;
            //orderModel.OrderStatus = o.Status;
            return View(o);
        }

        [HttpPost]
        public IActionResult ProcessOrder(Order o,int id)
        {
            ProcessOrderViewModel orderModel = new ProcessOrderViewModel();
            var orders = _orderService.GetAllOrders();
            var order = orders.FirstOrDefault(item => item.Id == o.Id);
            
            order.Status = o.Status;
            _orderService.UpdateOrder(order);
            return RedirectToAction("ViewOrderAdmin");
        }

    }
}

FoodAppMiniProject/Controllers/UserController.cs
using FoodAppMiniProject.Models;
using FoodAppMiniProject.Services;
using Microsoft.AspNetCore.Mvc;
using FoodAppMiniProject.Helpers;
using Newtonsoft.Json;

namespace FoodAppMiniProject.Controllers
{
    public class UserController : Controller
    {
        IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var user = SessionHelper.GetObjectFromJson<User>(HttpContext.Session, "admin");
            if (user != null)
            {
                ViewBag.Admin = user.Name;
            }
            else
            {
                return RedirectToRoute(new { controller = "Admin", action = "AdminLogin" });
            }

            return View(_userService.GetAllUsers());
        }

        [HttpGet]
        public IActionResult NewUser()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            User u = _userService.GetAllUsers().Where(item=>item.Id==id).FirstOrDefault();
            return View(u);
        }


        [HttpPost]
        public IActionResult NewUser(User u)
        {
            if (ModelState.IsValid)
            {
                bool res = _userService.CreateNewUser(u);
                if (res == true)
                {
                    TempData["type"] = "success";
                    TempData["msg"] = "User Registered Successfully";
                }
            }
            return RedirectToAction("NewUser");
        }

        //LOGIN
        [HttpGet]
        public IActionResult UserLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UserLogin(LoginViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                Console.WriteLine("Invalid creds");
                return View();
            }

            var user = _userService.FindByEmail(viewModel.Email);
        
            if(user != null)
            {
                bool verified = BCrypt.Net.BCrypt.Verify(viewModel.Password, user.Password);
                if (verified)
                {
                    var userSession = SessionHelper.GetObjectFromJson<User>(HttpContext.Session, "user");
                    if (userSession == null)
                    {
                        SessionHelper.SetObjectAsJson(HttpContext.Session, "user", user);
                    }
                    return RedirectToRoute(new { controller = "Home", action = "Index" });
                }
                else
                {
                    TempData["type"] = "danger";
                    TempData["msg"] = "Invalid Email Or Password";
                }
                return View();
            }
            else
            {
                TempData["type"] = "danger";
                TempData["msg"] = "Invalid Email Or Password";
                return View();
            }
            
        }

        [HttpGet]
        public IActionResult UserLogout()
        {
            HttpContext.Session.Remove("user");
            return RedirectToAction("UserLogin");
        }


        //Remote validation
        [HttpPost]
        public JsonResult doesUserEmailExist(string email)
        {
            var user = _userService.FindByEmail(email);
            return Json(user == null);
        }

        [HttpGet]
        public IActionResult DeleteUser(int id)
        {

            var user = SessionHelper.GetObjectFromJson<User>(HttpContext.Session, "admin");
            if (user != null)
            {
                ViewBag.Admin = user.Name;
            }
            else
            {
                return RedirectToRoute(new { controller = "Admin", action = "AdminLogin" });
            }


            bool res = _userService.DeleteUser(id);
            if (res == true)
            {
                TempData["type"] = "danger";
                TempData["msg"] = "User Deleted";
            }
            return RedirectToAction("Index");
        }

    }
}

FoodAppMiniProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Food App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FoodAppMiniProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Food App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" style="align-self:flex-end">
                        
                        @if (ViewBag.User != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="ViewCart">View Cart</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="ViewOrder">View Orders</a>
                            </li>
                        }

                        @if (ViewBag.User == null && ViewBag.Admin == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="UserLogin">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="NewUser">Register</a>
                            </li>
                        }

                        @if (ViewBag.User != null)
                        {
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark float-end" asp-area="" asp-controller="User" asp-action="UserLogout">Logout</a>
                            </li>
                        }

                        @if (ViewBag.Admin != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="ViewDishes">Dishes</a>
                            </li>

                              <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="ViewOrderAdmin">Orders</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AdminLogout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Food App
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>